"""initial schema

Revision ID: 121aeb06cc16
Revises: 
Create Date: 2026-07-16 11:28:07.550004
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '121aeb06cc16'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=True),
    sa.Column('mb_releasegroup_id', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('suggested', 'saved', 'wanted', 'acquiring', 'owned', 'dismissed', name='album_state'), nullable=False),
    sa.Column('provenance', sa.Enum('spotify_save', 'artist_watch', 'backfill', 'manual', name='provenance'), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verdict_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owned_beets_id', sa.String(), nullable=True),
    sa.Column('owned_link_source', sa.Enum('auto', 'manual', name='link_source'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_mb_releasegroup_id'), 'album', ['mb_releasegroup_id'], unique=False)
    op.create_index(op.f('ix_album_spotify_id'), 'album', ['spotify_id'], unique=True)
    op.create_table('play_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(), nullable=False),
    sa.Column('spotify_album_id', sa.String(), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_track_id', 'played_at', name='uq_play')
    )
    op.create_index(op.f('ix_play_history_played_at'), 'play_history', ['played_at'], unique=False)
    op.create_index(op.f('ix_play_history_spotify_album_id'), 'play_history', ['spotify_album_id'], unique=False)
    op.create_index(op.f('ix_play_history_spotify_track_id'), 'play_history', ['spotify_track_id'], unique=False)
    op.create_table('spotify_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_art',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_art')
    op.drop_table('spotify_auth')
    op.drop_index(op.f('ix_play_history_spotify_track_id'), table_name='play_history')
    op.drop_index(op.f('ix_play_history_spotify_album_id'), table_name='play_history')
    op.drop_index(op.f('ix_play_history_played_at'), table_name='play_history')
    op.drop_table('play_history')
    op.drop_index(op.f('ix_album_spotify_id'), table_name='album')
    op.drop_index(op.f('ix_album_mb_releasegroup_id'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
