"""add seen_release

Revision ID: 1a2b0f0119a2
Revises: 7318c4d2123e
Create Date: 2026-07-16 16:43:35.964618
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1a2b0f0119a2'
down_revision: str | None = '7318c4d2123e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seen_release',
    sa.Column('spotify_album_id', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('spotify_album_id')
    )
    op.create_index(op.f('ix_seen_release_artist_id'), 'seen_release', ['artist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seen_release_artist_id'), table_name='seen_release')
    op.drop_table('seen_release')
    # ### end Alembic commands ###
