"""add notification_state

Revision ID: 3d05fc480026
Revises: 1a2b0f0119a2
Create Date: 2026-07-16 16:52:58.966670
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3d05fc480026'
down_revision: str | None = '1a2b0f0119a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reauth_notified', sa.Boolean(), nullable=False),
    sa.Column('triage_notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_state')
    # ### end Alembic commands ###
