"""add download_import

Revision ID: 5cc50513cfef
Revises: 3d05fc480026
Create Date: 2026-07-16 17:09:19.270853
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5cc50513cfef'
down_revision: str | None = '3d05fc480026'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('download_dir', sa.String(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('matched_album_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('detected', 'imported', 'failed', name='import_state'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_album_id'], ['album.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_import_torrent_hash'), 'download_import', ['torrent_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_import_torrent_hash'), table_name='download_import')
    op.drop_table('download_import')
    # ### end Alembic commands ###
