"""add album.artist_id

Revision ID: 7318c4d2123e
Revises: fc783ad913b6
Create Date: 2026-07-16 16:08:49.926599
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7318c4d2123e'
down_revision: str | None = 'fc783ad913b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('artist_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_album_artist_id'), 'album', ['artist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_album_artist_id'), table_name='album')
    op.drop_column('album', 'artist_id')
    # ### end Alembic commands ###
