"""add album.art_url

Revision ID: e47f59256cda
Revises: 121aeb06cc16
Create Date: 2026-07-16 12:07:45.679438
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e47f59256cda'
down_revision: str | None = '121aeb06cc16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('art_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'art_url')
    # ### end Alembic commands ###
