"""add album.snoozed_until

Revision ID: fc783ad913b6
Revises: e47f59256cda
Create Date: 2026-07-16 14:24:22.824026
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fc783ad913b6'
down_revision: str | None = 'e47f59256cda'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'snoozed_until')
    # ### end Alembic commands ###
